### ISSUE TITLE
Docker build fails with "ERROR: Cannot locate specified Dockerfile: Dockerfile"

### ISSUE THREAD

**Issue by DetermineAbsurd** [nichobi/sponsorblockcast#12]
I had cURLed the docker-compose.yaml file from the repo and am able to pull, but not able to build. This is the error that I get when running the command `docker-compose build`.

**Comment by nichobi** [comment]
I'm not very familiar with docker, the support here was contributed by @Ceralor. Looks to me like you need the [Dockerfile](https://github.com/nichobi/sponsorblockcast/blob/main/Dockerfile) in the same directory too, and perhaps you would also need the other files from the repo. Try cloning the whole repo, instead of just the compose file.

**Comment by 9Mad-Max5** [comment]
The docker-compose needs always to be executed in the folder where the docker-compose.yml is located.
The same is it with docker build commands.

**Comment by KayOhtie** [comment]
Yep, as @9Mad-Max5 said. I can edit the section of the README.md to make this clearer.

**Comment by DetermineAbsurd** [comment]
Cloning the entire repo is what worked for me as the dockerfile itself from the repo is what it needed lol. Would recommend making that more explicit in the README so you don't have more people like me raising the same question haha.

**Comment by claabs** [comment]
The repo now has a prebuilt Docker image, so getting set up is much easier. See the [updated docker-compose.yml](https://www.github.com/nichobi/sponsorblockcast/tree/main/docker-compose.yaml) for an example.

**Comment by nichobi** [comment]
Thanks, claabs! I'll close this issue for now.
