### ISSUE TITLE
cannot open .segments: No such file

### ISSUE THREAD

**Issue by joszz** [nichobi/sponsorblockcast#16]
I installed sponsorblockcast manually and get the following error;
/usr/bin/sponsorblockcast: 33: cannot open .segments: No such file

not sure what I'm doing wrong here?
I would love to get this to work! any steps I can take to debug this?
I'm casting to a Shield TV and this script is running on a Ubuntu Server 20 box.

I saw this commit, I'm already running that latest change (just installed this last week);
https://github.com/nichobi/sponsorblockcast/commit/eb629e49b02d3cb90c77461dc4bfc0866e929afb

**Comment by joszz** [comment]
ah the Status in watch doesn't contain a videoId...

Status: >> YouTube (PLAYING), title="We Might Need a Wi-Fi Upgrade - Juniper Networks Showcase", artist="Linus Tech Tips", time remaining=94.21s/624.92s, volume=0.87, muted=false

That's an example of a status I get. I guess that this will not work for me?

**Comment by joszz** [comment]
Might be a way to use the API to retrieve the video id by searching the title/artist.
I'm not well versed in bash scripting, otherwise I would give it a try myself.

Although this would be a bit of fuzzy logic (what if video with same title for example, not sure if tou can search on artist with the api), and not foolproof, so not sure if that's something to even consider.

**Comment by iMacThere4iAm** [comment]
I'm getting the same error when playing on a Chromecast with Google TV (4th gen) because `go-chromecast` doesn't return the youtube ContentID. This obviously breaks sponsorblock implementations which require it. Not sure if this is hardware dependent or something that Google has recently broken in the backend. 
Related issues: [vishen/go-chromecast/#112](https://github.com/vishen/go-chromecast/issues/112), [erdnaxeli/castblock#24](https://github.com/erdnaxeli/castblock/issues/24).
