### ISSUE TITLE
Add ability to decrease verbosity

### ISSUE THREAD

**Issue by hashworks** [nichobi/sponsorblockcast#4]
Currently, the script produces 2 log lines for every sleep interval. It's quite verbose and not really needed for normal usage. It would be great if one could limit it to warning / error log level only.

![example](https://fb.hash.works/rpgmtgfY/)

**Comment by nichobi** [comment]
This should already be addressed by the rewrite I did in 00b0fa6, so you likely just need to update. It should now only log when a new chromecast is detected and when content is skipped. 
I may eventually add several verbosity levels to ease debugging, though it hasn't been a high priority feature, since I haven't had many reports of issues.
